<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.CN.NET.Sdk/15.0.0">
    <PropertyGroup>
        <AssemblyName>Pipi</AssemblyName>
        <RootNamespace>Pipi</RootNamespace>
        <Version>0.1.0.0</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
</Project>
